version: '2'
services:
  halon-smtpd:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        HALON_REPO_USER: ${HALON_REPO_USER}
        HALON_REPO_PASS: ${HALON_REPO_PASS}
    volumes:
      - ../:/rabbitmq
      - ./smtpd/dist:/etc/halon
      - halon-spool:/var/spool/halon
  rabbitmq:
    image: rabbitmq:3
volumes:
  halon-spool: